
import os
import sys

def main():
    include_dir = "include"
    output_file = "src/std.c"
    
    if not os.path.exists(include_dir):
        print(f"Error: {include_dir} not found")
        sys.exit(1)

    headers = []
    for f in os.listdir(include_dir):
        if f.endswith(".h"):
            headers.append(f)
    headers.sort()
    
    with open(output_file, "w") as out:
        out.write('/* Auto-generated by scripts/embed_headers.py */\n')
        out.write('#include <string.h>\n\n')
        
        # Write content variables
        for h in headers:
            var_name = "std_" + h.replace(".", "_")
            with open(os.path.join(include_dir, h), "rb") as f:
                content = f.read()
            
            out.write(f'static const char {var_name}[] = {{\n')
            
            # Use byte array instead of string literal to avoid parser limits and hex escaping issues
            for i, val in enumerate(content):
                out.write(f'0x{val:02x}, ')
                if (i + 1) % 12 == 0:
                    out.write('\n')
            
            out.write('0x00\n};\n\n')
            
        out.write('char *get_std_header(char *filename) {\n')
        for h in headers:
            var_name = "std_" + h.replace(".", "_")
            out.write(f'    if (strcmp(filename, "{h}") == 0) return (char*){var_name};\n')
        out.write('    return NULL;\n')
        out.write('}\n')
    
    print(f"Generated {output_file} from {len(headers)} headers.")

if __name__ == "__main__":
    main()
